//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.17.0
//     from Assets/_Input/INPUTS.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/_Input/INPUTS.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @INPUTS: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @INPUTS()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""INPUTS"",
    ""maps"": [
        {
            ""name"": ""ZoeActions"",
            ""id"": ""9625a52b-ebe2-4ed3-a693-d10ed6a07021"",
            ""actions"": [
                {
                    ""name"": ""Mastery7"",
                    ""type"": ""Button"",
                    ""id"": ""7b07b951-208f-4ae3-a38d-8e041206c3af"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Surprised"",
                    ""type"": ""Button"",
                    ""id"": ""45c731e4-4e0d-457f-af08-11b0073662ca"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Angry"",
                    ""type"": ""Button"",
                    ""id"": ""b33d4389-93c6-4f58-bcda-d0bbe163ae23"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sad"",
                    ""type"": ""Button"",
                    ""id"": ""33dc5ccf-cf00-4085-914b-d8ea1a42fa26"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""24e94457-415e-485a-a1cc-a28f7fd8dd1e"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mastery7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5964418-cb88-4089-842a-d920f112f899"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Surprised"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34cb6065-77e0-4a51-97ad-5cc74f6ed380"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Surprised"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1a6222c-aab9-4f45-91e8-e9ddc30a684a"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Angry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0332558-cd62-451b-a8e6-507f34ecc0ac"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Angry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5c096fb-6889-4fff-99f4-e20ce0b4586a"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06d0dab0-e65d-403d-9e3f-15581494b2f2"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ZoeActions
        m_ZoeActions = asset.FindActionMap("ZoeActions", throwIfNotFound: true);
        m_ZoeActions_Mastery7 = m_ZoeActions.FindAction("Mastery7", throwIfNotFound: true);
        m_ZoeActions_Surprised = m_ZoeActions.FindAction("Surprised", throwIfNotFound: true);
        m_ZoeActions_Angry = m_ZoeActions.FindAction("Angry", throwIfNotFound: true);
        m_ZoeActions_Sad = m_ZoeActions.FindAction("Sad", throwIfNotFound: true);
    }

    ~@INPUTS()
    {
        UnityEngine.Debug.Assert(!m_ZoeActions.enabled, "This will cause a leak and performance issues, INPUTS.ZoeActions.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ZoeActions
    private readonly InputActionMap m_ZoeActions;
    private List<IZoeActionsActions> m_ZoeActionsActionsCallbackInterfaces = new List<IZoeActionsActions>();
    private readonly InputAction m_ZoeActions_Mastery7;
    private readonly InputAction m_ZoeActions_Surprised;
    private readonly InputAction m_ZoeActions_Angry;
    private readonly InputAction m_ZoeActions_Sad;
    /// <summary>
    /// Provides access to input actions defined in input action map "ZoeActions".
    /// </summary>
    public struct ZoeActionsActions
    {
        private @INPUTS m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public ZoeActionsActions(@INPUTS wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "ZoeActions/Mastery7".
        /// </summary>
        public InputAction @Mastery7 => m_Wrapper.m_ZoeActions_Mastery7;
        /// <summary>
        /// Provides access to the underlying input action "ZoeActions/Surprised".
        /// </summary>
        public InputAction @Surprised => m_Wrapper.m_ZoeActions_Surprised;
        /// <summary>
        /// Provides access to the underlying input action "ZoeActions/Angry".
        /// </summary>
        public InputAction @Angry => m_Wrapper.m_ZoeActions_Angry;
        /// <summary>
        /// Provides access to the underlying input action "ZoeActions/Sad".
        /// </summary>
        public InputAction @Sad => m_Wrapper.m_ZoeActions_Sad;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_ZoeActions; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="ZoeActionsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(ZoeActionsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="ZoeActionsActions" />
        public void AddCallbacks(IZoeActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_ZoeActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ZoeActionsActionsCallbackInterfaces.Add(instance);
            @Mastery7.started += instance.OnMastery7;
            @Mastery7.performed += instance.OnMastery7;
            @Mastery7.canceled += instance.OnMastery7;
            @Surprised.started += instance.OnSurprised;
            @Surprised.performed += instance.OnSurprised;
            @Surprised.canceled += instance.OnSurprised;
            @Angry.started += instance.OnAngry;
            @Angry.performed += instance.OnAngry;
            @Angry.canceled += instance.OnAngry;
            @Sad.started += instance.OnSad;
            @Sad.performed += instance.OnSad;
            @Sad.canceled += instance.OnSad;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="ZoeActionsActions" />
        private void UnregisterCallbacks(IZoeActionsActions instance)
        {
            @Mastery7.started -= instance.OnMastery7;
            @Mastery7.performed -= instance.OnMastery7;
            @Mastery7.canceled -= instance.OnMastery7;
            @Surprised.started -= instance.OnSurprised;
            @Surprised.performed -= instance.OnSurprised;
            @Surprised.canceled -= instance.OnSurprised;
            @Angry.started -= instance.OnAngry;
            @Angry.performed -= instance.OnAngry;
            @Angry.canceled -= instance.OnAngry;
            @Sad.started -= instance.OnSad;
            @Sad.performed -= instance.OnSad;
            @Sad.canceled -= instance.OnSad;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ZoeActionsActions.UnregisterCallbacks(IZoeActionsActions)" />.
        /// </summary>
        /// <seealso cref="ZoeActionsActions.UnregisterCallbacks(IZoeActionsActions)" />
        public void RemoveCallbacks(IZoeActionsActions instance)
        {
            if (m_Wrapper.m_ZoeActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="ZoeActionsActions.AddCallbacks(IZoeActionsActions)" />
        /// <seealso cref="ZoeActionsActions.RemoveCallbacks(IZoeActionsActions)" />
        /// <seealso cref="ZoeActionsActions.UnregisterCallbacks(IZoeActionsActions)" />
        public void SetCallbacks(IZoeActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_ZoeActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ZoeActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="ZoeActionsActions" /> instance referencing this action map.
    /// </summary>
    public ZoeActionsActions @ZoeActions => new ZoeActionsActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "ZoeActions" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="ZoeActionsActions.AddCallbacks(IZoeActionsActions)" />
    /// <seealso cref="ZoeActionsActions.RemoveCallbacks(IZoeActionsActions)" />
    public interface IZoeActionsActions
    {
        /// <summary>
        /// Method invoked when associated input action "Mastery7" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMastery7(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Surprised" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSurprised(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Angry" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAngry(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Sad" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSad(InputAction.CallbackContext context);
    }
}
